---
title: Grading Contract
output: github_document
params:
  weektwothursday: "2022-01-10"
  name: Adam Paul
---

```{r setup, include=FALSE}

# R Syllabus Scheduler

advdate <- function(obj,
                    adv,
                    topic =  NULL,
                    assignment=NULL,
                    unit="Module ") {
  tmon <- obj + 7*(adv-1)
  ttue <- obj + 1 + 7*(adv-1)
  twed <- obj + 2 + 7*(adv-1)
  tthu <- obj + 3 + 7*(adv-1)
  tfri <- obj + 4 + 7*(adv-1)
  tmon <- format(tmon, format="%m/%d")
  ttue <- format(ttue, format="%m/%d")
  twed <- format(twed, format="%m/%d")
  tthu <- format(tthu, format="%m/%d")
  tfri <- format(tfri, format="%m/%d")
  zadv <- sprintf("%02d", adv)

  if (is.null(topic)&is.null(assignment)){
    tmp <- paste(unit,zadv,sep='',", ", tmon," - ",tfri)
  } else if(!is.null(assignment)){
    if(assignment %in%
       c("Friday",
         "friday",
         "f",
         "fri",
         "FRI")
       ){
    tmp <- paste0(tfri)
  } else if(assignment %in%
            c("thursday",
              "Thursday",
              "thurs",
              "r",
              "R")){
    tmp <- paste0(tthu)
  }else if(assignment %in%
           c("wednesday",
             "Wednesday",
             "w",
             "wed",
             "W")
           ){
    tmp <- paste0(twed)
  } else if(assignment %in%
            c("Tuesday",
              "tues",
              "t",
              "Tue")){
    tmp <- paste0(ttue)
  }else if(assignment %in%
            c("monday",
              "Monday",
              "m")
            ){
    tmp <- paste0(tmon)
  }
  }else{
    tmp <- paste(unit,zadv,sep='',", ", tmon," - ",tfri, " : ", topic[adv])
    }
  return(tmp)
}


dayone <- as.Date(params$weekonemonday)

topic=c(
  "What is Data Science and Meet the Toolkit", 
  "Data and Visualization",
  "Grammar of data wrangling",
  "Data types and Data Transformations",
  "Tips for effective data visualization",
  "Scientific studies and confounding",#  "Spring Break",#  "",
  "Web scraping", 
  "Functions", 
  "Data and Ethics",
  "Fitting and interpreting models",
  "Prediction and overfitting", 
  "Cross validation", 
  "Quantifying uncertainty",
  "Interactive web apps",
  "Special Topics" 
  )

```

<!-- This contract is adapted from Annie Somerville's contract https://github.com/anniehsom -->



# Contract Grades – “A” Contract

I, `r params$name`, agree to :

1) Earn “Satisfactory” on 11 self-paced lab assignments on the schedule specified below.
	-  Satisfactory defined:
  	-  I have attempted all steps of the assignment. If unable to complete steps due to unresolved questions, I have asked questions in Github FAQs or zoom help session, or I have Googled the issue and shown effort to resolve questions;
  	-  I have checked that forked files, repos, or projects appear on my Github account and are accessible;
  	-  I feel like I have spent an adequate amount of time and energy on assignments; 
  	-  My presentation is professional and engaging.
2) Produce at least 10 “Satisfactory” portfolio pieces on the schedule specified below.
3) Complete a “Satisfactory” presentation on a portfolio piece. 10 minutes total in length.



## SCHEDULE

- [ ] `r advdate(dayone, 1, topic)`
  - Finish Lab 1 by 1/21
- [ ] `r advdate(dayone, 2, topic)`
  - Finish Lab 2 by 2/11
- [ ]  `r advdate(dayone, 3, topic)`
  - Finish Lab 3  by 2/11
- [ ] `r advdate(dayone, 4, topic)`
  - Finish Lab 4  by 2/11
- [ ] `r advdate(dayone, 5, topic)`
  - Finish Lab 5  by 4/28
- [ ] `r advdate(dayone, 6, topic)`
  - Finish Lab 6 by 4/28
  - Finish portfolio piece 1 by 3/25
      - Portfolio 1 will be setting up a markdown for the study 2 of my thesis study.
- [ ] `r advdate(dayone, 7, topic)`
  - Finish Lab 7 4/28
  - Finish portfolio piece 2 by 3/29
      - Portfolio 2 will be a practice of the prior markdown of my last semester thesis study, comparing it to my SPSS analysis.
- [ ] `r advdate(dayone, 8, topic)`
  - Finish Lab 8 by 4/28
  - Finish portfolio piece 3, 4, & 5 by 4/1
      - Portfolio 3 will be setting up a markdown for the study 1 of my thesis study.
      - Portfolio 4 will be running the analyses of my MAP, comparing them to my SPSS analysis.
      - Portfolio 5 will be a practice with my last semester thesis study data cleaning. Will come to class for help
- [ ] `r advdate(dayone, 9, topic)`
  - Finish Lab 9 by 4/28
  - Finish portfolio piece 6 by 4/6
      - Portfolio 6 will be the actual analysis of study 2 of my thesis study
- [ ] `r advdate(dayone, 10, topic)`
  - Finish Lab 10 by 4/28
  - Finish portfolio piece 7 by 4/22
      - Because I do not know when these data will be available, I am putting this at the end of the semester.
      - However, portfolio piece 7 will be the actual analysis of study 1 of my thesis study
- [ ] `r advdate(dayone, 11, topic)`
  - Finish Lab 11 by 4/28
  - Finish portfolio piece 8 by 4/8
      - Portfolio 8 will be creating graphs of data from thesis studies
- [ ] `r advdate(dayone, 12, topic)`
  - Finish portfolio piece 9 by 4/15
      - Portfolio 9 will be the creation of a markdown file that combines all of my thesis analyses and graphs into a single document for presentation.
- [ ] `r advdate(dayone, 13, topic)`
  - Finish portfolio piece 10 by 4/28
      - I have no idea what I should do for this one.
- [ ] `r advdate(dayone, 14, topic)`
  - Prepare presentation- any time after 4/20 (thesis defense)
- [ ] Portfolio completion and end-of-semester presentation
  - Due on 4/29

